package wallet

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/hashhog/blockbrew/internal/address"
	"github.com/hashhog/blockbrew/internal/consensus"
)

// TestW161Bug15MnemonicPersistedAndRecoverable pins the W161 BUG-15/17
// funds-loss fix: the BIP-39 mnemonic auto-generated by createwallet
// (Manager.CreateWallet) must be durably persisted INSIDE the wallet file
// before creation returns, must actually re-derive the wallet's master key,
// and must survive a simulated process restart (fresh Manager + reload from
// disk + re-save).
//
// Teeth (pre-fix behavior this test fails on): Manager.CreateWallet generated
// a fresh mnemonic and discarded it — CreateFromMnemonic derived the seed and
// dropped the words, SaveToFile persisted only masterKey.Key||ChainCode (a
// one-way derivation; the words are NOT recoverable from it), and the
// createwallet RPC returned only {name, warnings}. Net effect: the recovery
// phrase existed nowhere — not in the response, not on disk — so losing
// wallet.dat meant unrecoverable funds.
//
// Core parity bar (bitcoin-core/src/wallet/): CreateWallet persists the master
// secret in the wallet DB within the creation transaction, BEFORE the RPC
// returns (wallet.cpp::SetupDescriptorScriptPubKeyMans ->
// scriptpubkeyman.cpp::AddDescriptorKeyWithDB -> walletdb commit, fsynced).
// blockbrew's analog of that secret is the mnemonic; its analog of the wallet
// DB is the scrypt+AES-GCM-encrypted walletData JSON written atomically by
// SaveToFile, which Manager.CreateWallet already calls before returning.
//
// NOTE: this test deliberately uses only APIs that predate the fix
// (Manager.CreateWallet / LoadWallet, SaveToFile, decrypt, walletData,
// ValidateMnemonic, MnemonicToSeed, NewMasterKey, GetMasterFingerprint) so it
// compiles — and FAILS — on the un-fixed tree, proving it detects the bug.
func TestW161Bug15MnemonicPersistedAndRecoverable(t *testing.T) {
	dir := t.TempDir()
	const walletName = "bug15"
	const pw = "" // Manager.LoadWallet always loads with the empty password

	// readPersistedMnemonic decrypts the on-disk wallet file the same way
	// LoadFromFile does and returns the persisted walletData.Mnemonic. This is
	// the "persisted form survives in the on-disk file" assertion: the words
	// must live inside the encrypted envelope, not merely in process memory.
	readPersistedMnemonic := func(t *testing.T) string {
		t.Helper()
		ciphertext, err := os.ReadFile(filepath.Join(dir, "wallets", walletName, walletFileName))
		if err != nil {
			t.Fatalf("read wallet file: %v", err)
		}
		plaintext, err := decrypt(ciphertext, pw)
		if err != nil {
			t.Fatalf("decrypt wallet file: %v", err)
		}
		var data walletData
		if err := json.Unmarshal(plaintext, &data); err != nil {
			t.Fatalf("unmarshal wallet file: %v", err)
		}
		return data.Mnemonic
	}

	// ── 1. createwallet: fresh wallet, auto-generated mnemonic ──
	mgr := NewManager(dir, address.Mainnet, consensus.MainnetParams())
	w, err := mgr.CreateWallet(walletName, CreateWalletOpts{})
	if err != nil {
		t.Fatalf("CreateWallet: %v", err)
	}
	origFP, err := w.GetMasterFingerprint()
	if err != nil {
		t.Fatalf("GetMasterFingerprint: %v", err)
	}

	// ── 2. persist-before-return: the words must already be on disk ──
	persisted := readPersistedMnemonic(t)
	if persisted == "" {
		t.Fatalf("FUNDS-LOSS (W161 BUG-15): auto-generated mnemonic is absent from the wallet file — " +
			"the words were derived-from and discarded, so the user has no recovery path if wallet.dat is lost")
	}
	if !ValidateMnemonic(persisted) {
		t.Fatalf("persisted mnemonic fails BIP-39 validation: %q", persisted)
	}
	if got := len(strings.Fields(persisted)); got != 24 {
		t.Errorf("persisted mnemonic has %d words, want 24", got)
	}

	// ── 3. the persisted words must re-derive THIS wallet's master key ──
	// (a stored-but-wrong phrase would be a recovery that restores nothing)
	mk, err := NewMasterKey(MnemonicToSeed(persisted, ""))
	if err != nil {
		t.Fatalf("NewMasterKey from persisted mnemonic: %v", err)
	}
	if mk.Fingerprint() != origFP {
		t.Fatalf("persisted mnemonic re-derives fingerprint %x, wallet has %x — words do not recover these funds",
			mk.Fingerprint(), origFP)
	}

	// ── 4. simulated restart: fresh Manager, reload from disk ──
	mgr2 := NewManager(dir, address.Mainnet, consensus.MainnetParams())
	w2, err := mgr2.LoadWallet(walletName, nil)
	if err != nil {
		t.Fatalf("LoadWallet after restart: %v", err)
	}
	fp2, err := w2.GetMasterFingerprint()
	if err != nil {
		t.Fatalf("GetMasterFingerprint after restart: %v", err)
	}
	if fp2 != origFP {
		t.Fatalf("master key did not survive restart: %x != %x", fp2, origFP)
	}

	// ── 5. restart-survivability of the words themselves: a re-save from the
	// reloaded in-memory state must NOT drop the mnemonic from disk (i.e. load
	// restored it into memory, save re-persists it — otherwise the first
	// auto-flush after a restart would silently destroy the backup). ──
	if err := w2.SaveToFile(pw); err != nil {
		t.Fatalf("re-save after restart: %v", err)
	}
	if got := readPersistedMnemonic(t); got != persisted {
		t.Fatalf("mnemonic lost across restart+resave: on disk %q, want %q", got, persisted)
	}
}

// TestW161Bug15RestorePathPersistsSuppliedMnemonic proves the createwallet
// RESTORE path (caller-supplied words) persists them identically, so a
// restored wallet's file is just as self-recovering as a fresh one.
func TestW161Bug15RestorePathPersistsSuppliedMnemonic(t *testing.T) {
	dir := t.TempDir()
	mgr := NewManager(dir, address.Mainnet, consensus.MainnetParams())
	if _, err := mgr.CreateWallet("restored", CreateWalletOpts{Mnemonic: testMnemonic}); err != nil {
		t.Fatalf("CreateWallet(restore): %v", err)
	}

	ciphertext, err := os.ReadFile(filepath.Join(dir, "wallets", "restored", walletFileName))
	if err != nil {
		t.Fatalf("read wallet file: %v", err)
	}
	plaintext, err := decrypt(ciphertext, "")
	if err != nil {
		t.Fatalf("decrypt wallet file: %v", err)
	}
	var data walletData
	if err := json.Unmarshal(plaintext, &data); err != nil {
		t.Fatalf("unmarshal wallet file: %v", err)
	}
	if data.Mnemonic != testMnemonic {
		t.Fatalf("restored wallet persisted mnemonic %q, want %q", data.Mnemonic, testMnemonic)
	}
}
